version: "3.8"

services:
  example-backend:
    image: example-backend
    build: ./example-backend
    ports:
      - 127.0.0.1:8000:8000
    container_name: backend
  example-frontend:
    image: example-frontend
    build: ./example-frontend
    ports:
      - 127.0.0.1:5000:5000
    container_name: frontend
